# ECE 2112: Experiment 2: Numerical Python (NUMPY)

#### Balagtas, Jacob T.
#### 2ECE-B

# A. REPRODUCIBLE NORMALIZATION PROBLEM

In [60]:
import numpy as np

In [61]:
np.random.seed(2112)
X = np.random.randint(10, 101, size=(5, 5))
X

array([[48, 11, 15, 67, 21],
       [11, 41, 13, 66, 24],
       [71, 79, 53, 67, 70],
       [77, 35, 91, 19, 96],
       [35, 54, 37, 41, 17]])

In [63]:
X_mean = X.mean()
X_std = X.std()

In [64]:
X_normalized = (X - X_mean) / X_std

In [73]:
print(X_normalized)

[[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]


In [74]:
X.mean()

np.float64(46.36)

In [75]:
X.std()

np.float64(25.864075471588002)

In [71]:
X_normalized.mean()

np.float64(0.0)

In [72]:
X_normalized.std()

np.float64(0.9999999999999999)

In [51]:
np.save("X_normalized.npy", X_normalized)

# B. CUBES DIVISIBLE BY 4 PROBLEM

In [76]:
import numpy as np

In [77]:
C = (np.arange(1,101) ** 3).reshape(10,10)

In [78]:
div_by_4 = C[C % 4 == 0]

In [79]:
print("Shape of C:", C.shape)

Shape of C: (10, 10)


In [80]:
print("div_by_4 array:", div_by_4)

div_by_4 array: [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]


In [81]:
print("Number of Selected Elements:", div_by_4.size)

Number of Selected Elements: 50


In [82]:
np.save("div_by_4.npy", div_by_4)

# C. ABOVE-MEAN SQUARES PROBLEM

In [83]:
import numpy as np

In [84]:
S = (np.arange(1,37) ** 2).reshape(6,6)

In [85]:
S_mean = S.mean()

In [86]:
above_mean = S[S > S_mean]

In [90]:
print("S: ")
print(S)

S: 
[[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]


In [91]:
print("S_mean: ")
print(S_mean)

S_mean: 
450.1666666666667


In [92]:
print("above_mean: ")
print(above_mean)

above_mean: 
[ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]


In [93]:
print("Number of Selected Elements: ")
print(above_mean.size)

Number of Selected Elements: 
15


In [94]:
np.save("above_mean.npy", above_mean)